# -*- coding: utf-8 -*-
"""절감 시나리오

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DYhKY9wocFSGsDtshakelesHn8AlQsiL
"""

# GPT API 연결
from getpass import getpass
import os
from openai import OpenAI

# 입력 (API 입력해야함)
os.environ["OPENAI_API_KEY"] = getpass("Enter your OpenAI API key: ")
client = OpenAI(api_key=os.environ["OPENAI_API_KEY"])

# 절감 시나리오
def generate_reduction_scenario(df, forecast_series, model_name="gpt-4o-mini"):
    recent_mode = df["mode"].iloc[-1]
    recent_em = float(df["emission_kg"].iloc[-1])


    # 예측값 3개월
    pred3 = [float(x) for x in forecast_series.values.tolist()]

    # 최근 3개월 평균(목표 자동 설정 같은 로직도 프롬프트에 넣기 좋음)
    recent3_avg = float(df["emission_kg"].iloc[-3:].mean())
    target = recent3_avg * 0.95  # 예: -5% 목표

    prompt = f"""
아래는 한 사용자의 월별 교통 탄소배출 데이터 요약이다.

[데이터]
- 최근 통학 수단: {recent_mode}
- 최근 월 배출량: {recent_em:.2f} kgCO2e
- 최근 3개월 평균 배출량: {recent3_avg:.2f} kgCO2e
- 이번 달 권장 목표(최근3개월 평균 대비 -5%): {target:.2f} kgCO2e
- 향후 3개월 예측 배출량(kgCO2e): {pred3}

[목표]
사용자가 "이번 달 권장 목표({target:.2f} kgCO2e)"에 도달하도록,
실행 가능한 교통 절감 행동을 매우 구체적으로 제안하라.

[출력 규칙 - 반드시 지킬 것]
- 반드시 아래 3개 섹션 제목을 그대로 출력할 것:
  1. 탄소 배출량 요약
  2. 탄소 절감 전략
  3. 추천 전략 Top 3
- 마크다운 기호 사용 금지(**, *, #, -, ``` 등)
- 각 섹션은 번호/문장만 사용 (불릿 사용 금지)
- 너무 길게 쓰지 말되, 각 전략은 반드시 "정량 정보"를 포함할 것

[1. 탄소 배출량 요약]
1) 최근 배출 특성을 2~3문장으로 요약하라.
2) 다음 1문장을 반드시 포함하라:
   "이번 달 목표는 최근 3개월 평균 대비 약 5% 감축이다."

[2. 탄소 절감 전략]
아래 형식으로 4~5개 전략을 제시하라. (전략마다 동일한 형식 유지)

(전략 n)
- 행동: (예: 지하철/버스/도보/자전거 전환, 환승 방식, 택시 대체 등)
- 실행 단위: (반드시 숫자 포함: 주당 X회 / 월 X일 / 하루 X분 / 거리 Xkm / 비율 X%)
- 기간: (예: 이번 달 4주 동안 / 향후 2주간 등)
- 예상 절감량: (반드시 숫자 포함: 월 ○○ kgCO2e 또는 ○%)
- 근거(1줄): "기준선(현재 패턴) 대비 이동수단 배출계수 차이 + 전환 거리/횟수"를 근거로 간단히 설명

추가 제약:
- “대중교통을 이용하세요” 같은 추상적 문장 금지
- 사용자가 바로 따라할 수 있게 "요일/상황 예시"를 1개 이상 포함할 것
  (예: 월/수/금은 버스, 화/목은 지하철+도보 등)

[3. 추천 전략 Top 3]
1) 위 전략 중 목표({target:.2f} kgCO2e) 달성에 가장 효과적인 Top-3를 선정하라.
2) 각 Top-3 항목은 반드시 아래 형식을 지켜라:

(Top k)
- 추천 전략명: (한 줄 제목)
- 오늘부터 실행 플랜: (이번 주에 언제/얼마나 할지 숫자로 제시)
- 기대 절감량: (월 기준 숫자)
- 우선순위 근거: 효과(1~5), 난이도(1~5), 비용(1~5) 점수를 제시하고 1문장으로 이유 설명

[문장 톤]
학생/개인 대상, 현실적으로 가능한 수준으로 작성하라.
"""

    resp = client.chat.completions.create(
        model=model_name,
        messages=[{"role": "user", "content": prompt}],
    )
    return resp.choices[0].message.content

scenario_text = generate_reduction_scenario(df, forecast_series)
scenario_text

#pdf 자동 생성
!pip install reportlab

# pdf 마크다운 제거 함수
import re

def clean_markdown_for_pdf(text: str) -> str:
    if text is None:
        return ""

    # Bold/Italic 마크다운 제거
    text = text.replace("**", "").replace("__", "")
    text = text.replace("*", "").replace("_", "")

    # 헤더(###, #### 등) 제거
    text = re.sub(r"^\s*#{1,6}\s*", "", text, flags=re.MULTILINE)

    # 불릿 기호 통일 (-, • 등) -> " - "
    text = re.sub(r"^\s*[-•]\s*", "- ", text, flags=re.MULTILINE)

    # 연속 공백 정리
    text = re.sub(r"[ \t]+", " ", text)

    return text.strip()

# 한글 사용을 위한 폰트 등록
!apt-get -y install fonts-nanum

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.pagesizes import letter
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib.fonts import addMapping
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

pdfmetrics.registerFont(TTFont("NanumGothic", "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"))
pdfmetrics.registerFont(TTFont("NanumGothicBold", "/usr/share/fonts/truetype/nanum/NanumGothicBold.ttf"))

addMapping("NanumGothic", 0, 0, "NanumGothic")       # normal
addMapping("NanumGothic", 1, 0, "NanumGothicBold")   # bold

styles = getSampleStyleSheet()
styles = getSampleStyleSheet()

title_style = ParagraphStyle(
    "KoreanTitle",
    parent=styles["Title"],
    fontName="NanumGothic",
    fontSize=18,
    leading=22,
)

section_style = ParagraphStyle(
    "KoreanSection",
    parent=styles["Heading2"],
    fontName="NanumGothic",
    fontSize=13,
    leading=18,
)

h2 = ParagraphStyle(
    "KoreanH2",
    parent=styles["Heading2"],
    fontName="NanumGothic",
    fontSize=14,
    leading=18,
)

base = ParagraphStyle(
    "KoreanBody",
    parent=styles["BodyText"],
    fontName="NanumGothic",
    fontSize=11,
    leading=14,
)

#절감 시나리오 레포트 pdf 생성
def make_pdf_report(df, forecast, scenario, filename="carbon_report.pdf"):

    doc = SimpleDocTemplate(filename, pagesize=letter)
    story = []

    # 제목
    story.append( Paragraph("<b>Carbon Emission Analysis Report</b>", title_style))
    story.append(Spacer(1, 24))

    # 1. Summary
    text1 = f"""
    분석 기간: {df['date'].iloc[0].date()} ~ {df['date'].iloc[-1].date()}<br/>
    최근 월 배출량: {df['emission_kg'].iloc[-1]:.2f} kgCO2e<br/>
    통학 수단: {df['mode'].iloc[-1]}<br/>
    """
    story.append(Paragraph(text1, base))
    story.append(Spacer(1, 16))

    # 2. Forecast
    story.append(Paragraph("1. 향후 탄소 배출량 예측", section_style))

    forecast_str = "<br/>".join(
        [f"{d.date()}: {v:.2f} kgCO2e" for d, v in forecast.items()]
    )

    story.append(Paragraph(forecast_str, base))
    story.append(Spacer(1, 16))

    # 3. Reduction Scenario
    story.append(Paragraph("2. AI 기반 절감 시나리오 제안", section_style))

    story.append(
        Paragraph(
            scenario.replace("\n", "<br/>"),
            base
        )
    )
    doc.build(story)
    return filename

#실행
from datetime import datetime

filename = f"carbon_report_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
pdf_path = make_pdf_report(df, forecast_series, scenario_text, filename)
pdf_path

#파일 다운로드
from google.colab import files
files.download(pdf_path)